apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-api
spec:
  selector:
    matchLabels:
      app: crud-api
  replicas: 1
  template:
    metadata:
      labels:
        app: crud-api
    spec:
      containers:
        - name: app
          image: thiedebr/crud-api:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: crud-api
  labels:
    app: crud-api
spec:
  ports:
    - name: crud-api
      nodePort: 31175
      port: 80
      targetPort: 8887
  selector:
    app: crud-api
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-api
  annotations:
    kubernetes.io/rewrite-target: $1
spec:
  rules:
    - host: myk8s.com
      http:
        paths:
          - path: /api(.*)
            pathType: Prefix
            backend:
              service:
                name: crud-api
                port:
                  number: 8887
