version: "3.3"

services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    expose:
      - "8887"
    restart: always

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    expose:
      - "80"
    restart: always
