apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-ui
spec:
  selector:
    matchLabels:
      app: crud-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: crud-ui
    spec:
      containers:
        - name: app
          image: thiedebr/playground:crud-ui
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: crud-ui
  labels:
    app: crud-ui
spec:
  ports:
    - port: 80
      name: crud-ui
      targetPort: 80
  selector:
    app: crud-ui
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-ui
  annotations:
    kubernetes.io/rewrite-target: $1
spec:
  rules:
    - host: myk8s.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: crud-ui
                port:
                  number: 80
