VAGRANTFILE_API_VERSION = "2"
IMAGE_NAME = "bento/ubuntu-16.04"
NB_WORKERS = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.boot_timeout = 1800
    config.vm.synced_folder '../../', '/vagrant'

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
    
    config.vm.define "k8s-controller" do |controller|
        controller.vm.box = IMAGE_NAME
        controller.vm.network "private_network", ip: "10.0.0.10"
        controller.vm.hostname = "k8s-controller"
        controller.vm.network :forwarded_port, host_ip: "127.0.0.1", host: "6443", guest: "6443"
        controller.vm.network :forwarded_port, host_ip: "127.0.0.1", host: "8888", guest: "8080"
        controller.vm.network :forwarded_port, host_ip: "127.0.0.1", host: "8880", guest: "80"
        controller.vm.network :forwarded_port, host_ip: "127.0.0.1", host: "8443", guest: "443"
        controller.vm.provision "shell", privileged: true, path: "kubernetes-setup/prepare-controller.sh"
    end

    (1..NB_WORKERS).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "10.0.0.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "shell", privileged: true, path: "kubernetes-setup/prepare-node.sh"
        end
    end
end
